In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from datasets import load_dataset
dataset = load_dataset("AiresPucrs/News-Category-Dataset")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/847 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 27.5MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/209527 [00:00<?, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'labels'],
        num_rows: 209527
    })
})

In [ ]:
df=dataset['train'].to_pandas()
df

                                                     text     labels
0       Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS
1       American Airlines Flyer Charged, Banned For Li...  U.S. NEWS
2       23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY
3       The Funniest Tweets From Parents This Week (Se...  PARENTING
4       Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS
...                                                   ...        ...
209522  RIM CEO Thorsten Heins' 'Significant' Plans Fo...       TECH
209523  Maria Sharapova Stunned By Victoria Azarenka I...     SPORTS
209524  Giants Over Patriots, Jets Over Colts Among  M...     SPORTS
209525  Aldon Smith Arrested: 49ers Linebacker Busted ...     SPORTS
209526  Dwight Howard Rips Teammates After Magic Loss ...     SPORTS

[209527 rows x 2 columns]

In [ ]:

df.isna().sum()

text      0
labels    0
dtype: int64

In [ ]:
df['labels'].nunique()

42

In [ ]:

df['labels'].value_counts()

labels
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64

In [ ]:
#feature selection

In [ ]:

X=np.array(df['text'])

In [ ]:
y=np.array(df['labels'])

In [ ]:
X.shape

(209527,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train,

(array(["Owners Discuss Removing Trump's Name From Manhattan Highrise: Report The building's residents are getting jittery about reduced values in properties linked to the twice-impeached former president.",
        'Mandy Moore Shows Off Shiny New Engagement Ring At 2017 Emmy Awards We couldn’t take our eyes off her shiny new accessory',
        'Israel and Her Minorities If Israel wishes to be "a light unto the nations" she must put the brakes on this growing intolerant tendency towards 20 percent of its own population. The tragic consequences if she does not will be hard to stop.',
        ..., '9 Film Franchises That Made It To 9 Installments ',
        "VIDEO: Your Makeup Has WHAT In It? Pucker up--we're about to take you into the secret world of makeup. Read more on www.weather.com",
        'La. Teacher Suspected Of Having Sex With Students '], dtype=object),)

In [ ]:
X_test,

(array(["What If We Were All Family Generation Changers? What if, in doing so, we won't just create new opportunities for ourselves, we'll also uncover ways to create new opportunities for our families that may not have otherwise existed?",
        'Firestorm At AOL Over Employee Benefit Cuts It should have been a glorious week for AOL chief executive Tim Armstrong. His company’s quarterly earnings, announced Thursday',
        'Dakota Access Protesters Arrested As Deadline Passes To Depart Camp A few protesters who refused to leave remained at the site Thursday.',
        ...,
        "5 Things You Should Buy At Estate Sales (And 3 To Skip) Cookware Take a very, very close look before you tote that darling enamelware fondue pot home. If there's even a tiny chip",
        "Ask Oyster: Where Can I Find Single Ladies? (PHOTOS) We look to answer the question: I'm looking for high-end resorts with an abundance of single ladies.",
        'The Future Of The World Is At Stake Diversity is key to real innovation.'],
       dtype=object),)

In [ ]:
y_train

array(['POLITICS', 'ENTERTAINMENT', 'WORLDPOST', ..., 'ENTERTAINMENT',
       'STYLE & BEAUTY', 'CRIME'], dtype=object)

In [ ]:
y_train

array(['POLITICS', 'ENTERTAINMENT', 'WORLDPOST', ..., 'ENTERTAINMENT',
       'STYLE & BEAUTY', 'CRIME'], dtype=object)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(
    max_features=150000,
    ngram_range=(1, 2),
    stop_words='english',
    token_pattern=r'\b[a-z]+\b',
    lowercase=True)
V_X_train= vectorizer.fit_transform(X_train)
V_X_test= vectorizer.transform(X_test)

In [ ]:
feature_names = vectorizer.get_feature_names_out()
print("150 sample feature names:", feature_names[50:150])

150 sample feature names: ['abdel' 'abdel fattah' 'abdicated' 'abdication' 'abdomen' 'abdominal'
 'abdominal muscles' 'abducted' 'abducting' 'abduction' 'abdul'
 'abdul jabbar' 'abdul rahman' 'abdul s' 'abdulaziz' 'abdullah' 'abe'
 'abedin' 'abel' 'abercrombie' 'abercrombie fitch' 'aberdeen' 'abetting'
 'abhorrent' 'abide' 'abiding' 'abigail' 'abigail breslin' 'abilities'
 'ability' 'ability change' 'ability connect' 'ability cope'
 'ability create' 'ability develop' 'ability focus' 'ability function'
 'ability inspire' 'ability know' 'ability learn' 'ability listen'
 'ability live' 'ability make' 'ability relax' 'ability think'
 'ability transform' 'ability use' 'ability work' 'abject'
 'abject failure' 'ablaze' 'able' 'able accomplish' 'able afford'
 'able appreciate' 'able bodied' 'able buy' 'able change' 'able choose'
 'able control' 'able count' 'able enjoy' 'able enter' 'able help'
 'able hold' 'able identify' 'able let' 'able live' 'able look'
 'able make' 'able meet' 'able notice' 'able pass' 'able pay'
 'able predict' 'able provide' 'able reach' 'able read' 'able recognize'
 'able remember' 'able say' 'able share' 'able solve' 'able speak'
 'able spend' 'able stand' 'able stay' 'able stop' 'able survive'
 'able talk' 'able tell' 'able things' 'able turn' 'able use' 'able vote'
 'able walk' 'able wear' 'able work' 'able write' 'abnormal']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

In [ ]:
y_train_encoded

array([24, 10, 41, ..., 10, 30,  6])

In [ ]:
y_test_encoded

array([18,  3, 24, ..., 17, 34, 39])

In [ ]:
from sklearn.svm import LinearSVC
model = LinearSVC(dual='auto')
model.fit(V_X_train, y_train_encoded)

LinearSVC()

In [ ]:
y_pred = model.predict(V_X_test)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:", accuracy_score(y_test_encoded, y_pred))
print("Classification Report:\n", classification_report(y_test_encoded, y_pred,zero_division=0))

Accuracy: 0.6190521643678709
Classification Report:
               precision    recall  f1-score   support

           0       0.36      0.24      0.28       293
           1       0.30      0.17      0.22       275
           2       0.54      0.43      0.48       889
           3       0.51      0.48      0.49      1216
           4       0.46      0.43      0.44       202
           5       0.55      0.45      0.49      1022
           6       0.54      0.58      0.56       713
           7       0.55      0.33      0.41       202
           8       0.79      0.76      0.77       664
           9       0.43      0.31      0.36       209
          10       0.65      0.76      0.70      3419
          11       0.54      0.27      0.36       313
          12       0.43      0.15      0.22       263
          13       0.62      0.71      0.66      1270
          14       0.41      0.23      0.30       270
          15       0.37      0.33      0.35       532
          16       0.35      0.24      0.29      1302
          17       0.76      0.75      0.75       879
          18       0.38      0.30      0.33       673
          19       0.64      0.35      0.45       238
          20       0.59      0.49      0.54       607
          21       0.52      0.41      0.46       355
          22       0.52      0.63      0.57      1768
          23       0.40      0.25      0.31       795
          24       0.73      0.84      0.78      7155
          25       0.75      0.73      0.74      1262
          26       0.58      0.49      0.53       530
          27       0.59      0.54      0.56       424
          28       0.70      0.76      0.73      1014
          29       0.50      0.27      0.35       464
          30       0.75      0.83      0.79      1975
          31       0.33      0.18      0.23       427
          32       0.54      0.47      0.50       398
          33       0.46      0.44      0.45       741
          34       0.70      0.81      0.75      2021
          35       0.39      0.12      0.19       269
          36       0.76      0.78      0.77       709
          37       0.38      0.30      0.34       550
          38       0.59      0.76      0.67      3672
          39       0.43      0.31      0.36       727
          40       0.48      0.37      0.42       665
          41       0.46      0.32      0.38       534

    accuracy                           0.62     41906
   macro avg       0.53      0.46      0.48     41906
weighted avg       0.60      0.62      0.60     41906

In [ ]:
# Broccoli on Pizza Sparks Heated Debate: Superfood Topping or Culinary Crime?

In [ ]:

newdata = vectorizer.transform([
    'Broccoli on Pizza Sparks Heated Debate: Superfood Topping or Culinary Crime?'
])

# Predict and decode the label
newPred = model.predict(newdata)
decoded = le.inverse_transform(newPred)

# Display result
print("Predicted vector:", newdata.toarray())
print("Predicted category:", decoded)

Predicted vector: [[0. 0. 0. ... 0. 0. 0.]]
Predicted category: ['FOOD & DRINK']